import './globals.css';
import RootProvider from '@/providers/Root.provider';
import type {Metadata} from 'next';
import {type FC} from 'react';

export const metadata: Metadata = {
  title: 'moodly',
  description: 'Generated by create next app'
};

const RootLayout: FC<{children: React.ReactNode}> = ({children}) => {
  return (
    <html lang="en">
      <body>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
};

export default RootLayout;
